# Generated by Django 2.2.5 on 2019-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='group',
            field=models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
