# Generated by Django 2.2.5 on 2019-10-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0002_auto_20191008_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentGroup', models.PositiveSmallIntegerField(default=1)),
                ('childGroup', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
