# Generated by Django 2.2.5 on 2019-10-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0003_groupgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group',
            new_name='id',
        ),
    ]
