# Generated by Django 2.2.5 on 2019-10-10 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0004_auto_20191010_0021'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupGroup',
        ),
    ]
