# Generated by Django 2.2.5 on 2019-10-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0008_christian_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='menLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FRNChurchStructure.Christian'),
        ),
    ]
