# Generated by Django 2.2.5 on 2019-10-10 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0009_group_menleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='womenLeader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='femaleLeader', to='FRNChurchStructure.Christian'),
        ),
    ]
