# Generated by Django 2.2.5 on 2019-10-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0010_group_womenleader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='christian',
            name='dateOfBaptism',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
