# Generated by Django 2.2.5 on 2019-11-07 18:43

from django.db import migrations, models
#import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0012_auto_20191011_0118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                #('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
