# Generated by Django 2.2.5 on 2019-11-07 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0014_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FRNChurchStructure.Contact'),
        ),
    ]
