# Generated by Django 2.2.5 on 2019-11-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0016_person_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
