# Generated by Django 2.2.5 on 2019-11-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0019_auto_20191113_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FRNChurchStructure.Contact'),
        ),
    ]
