# Generated by Django 2.2.5 on 2019-11-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0021_auto_20191113_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='menLeader',
        ),
        migrations.RemoveField(
            model_name='group',
            name='womenLeader',
        ),
        migrations.AddField(
            model_name='person',
            name='maritalStatus',
            field=models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed')], default='S', max_length=1),
        ),
    ]
