# Generated by Django 2.2.5 on 2019-11-16 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0022_auto_20191115_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FRNChurchStructure.Contact'),
        ),
    ]
