# Generated by Django 2.2.5 on 2019-11-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0023_auto_20191116_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='person',
            name='secondName',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
