# Generated by Django 2.2.5 on 2019-11-22 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FRNChurchStructure', '0024_auto_20191116_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
